---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  # XRDs must be named 'x<plural>.<group>'
  name: xs3buckets.crossplane.jonashackt.io
spec:
  # This XRD defines an XR in the 'crossplane.jonashackt.io' API group.
  # The XR or Claim must use this group together with the spec.versions[0].name as it's apiVersion, like this:
  # 'crossplane.jonashackt.io/v1alpha1'
  group: crossplane.jonashackt.io
  
  # XR names should always be prefixed with an 'X'
  names:
    kind: XS3Bucket
    plural: xs3buckets
  
  # This type of XR offers a claim, which should have the same name without the 'X' prefix
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  
  # The keys the XR writes to it's connection secret
  # which will act as a filter during aggregation of the connection secret from
  # composed resources.
  connectionSecretKeys:
    - secretKey
    - accessKey
    - host
  
  # default Composition when none is specified (must match metadata.name of a provided Composition)
  # e.g. in composition.yaml
  defaultCompositionRef:
    name: s3bucket

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    # OpenAPI schema (like the one used by Kubernetes CRDs). Determines what fields
    # the XR (and claim) will have. Will be automatically extended by crossplane.
    # See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
    # for full CRD documentation and guide on how to write OpenAPI schemas
    schema:
      openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          # We define 2 needed parameters here one has to provide as XR or Claim spec.parameters
          properties:
            bucketName:
              type: string
            region:
              type: string
          required:
            - bucketName
            - region