name: provision

on: [push]

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_DEFAULT_REGION: 'eu-central-1'

jobs:
  provision-kind-with-crossplane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install kind (see https://kind.sigs.k8s.io) & crossplane CLI
        run: |
          brew install kind

          echo "Install crossplane CLI & check if it's working"
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
          sudo mv kubectl-crossplane /usr/local/bin
          kubectl crossplane --help

      - name: Spin up kind cluster & try to use the cluster
        run: |
          kind create cluster --image kindest/node:v1.23.0 --wait 5m

          echo "Let's try to access our kind cluster via kubectl"
          kubectl get nodes
      
      - name: Install crossplane via Helm
        run: |
          echo "Create a namespace for crossplane"
          kubectl create namespace crossplane-system

          echo "Install crossplane via Helm"
          helm repo add crossplane-stable https://charts.crossplane.io/stable
          helm repo update
          helm upgrade --install crossplane --namespace crossplane-system crossplane-stable/crossplane

      - name: Check crossplane status
        run: |
          helm list -n crossplane-system
          kubectl get all -n crossplane-system
      